---
title: "Shiny Example"
author: "James L. Adams"
date: "3/10/2017"
runtime: shiny
output: html_document
---

## YAML Header
```
---
title: "Shiny Example"
author: "James L. Adams"
date: "3/10/2017"
runtime: shiny
output: html_document
---
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Live Data Source
```{r, warning=FALSE}
# Load necessary libraries
library(shiny)
library(leaflet)
library(jsonlite)

# Get Data every ~5 seconds
geojson <- reactivePoll(5000, session,
                        checkFunc = function(){
                          Sys.time()
                        },
                        valueFunc = function(){
                            readLines("https://wanderdrone.appspot.com/", warn = FALSE) %>%
                              paste(collapse = "\n") %>%
                              fromJSON(simplifyVector = FALSE)
                        }
                      )
```

## Create and Update Map
```{r live}

# Create map
output$leaflet <- renderLeaflet({
  leaflet() %>%
    addTiles()
})

# Update map when data updates
observe({
  leafletProxy("leaflet") %>%
    clearGeoJSON() %>%
    addGeoJSON(geojson()) %>%
    fitBounds(lng1 = max(geojson()$geometry$coordinates[[1]]) + 5,
              lat1 = max(geojson()$geometry$coordinates[[2]]) + 5,
            lng2 = min(geojson()$geometry$coordinates[[1]]) - 5,
            lat2 = min(geojson()$geometry$coordinates[[2]]) - 5)
})

leafletOutput("leaflet")

```

\nbsp